name: Test CI

on:  
  pull_request:
    branches:
      - master

jobs:  
  cobacoba:
    name: Test Case
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Perintah Linux
        run: |
          git status
          id
          ls -lah
          echo "Halo gais"